### ISSUE TITLE
Если удалять сообщения с редактированием среди которых был стикер то бот ломается....

### ISSUE THREAD

**Issue by fgff** [P2LOVE/VK-UserSide-Bot#1]
Пишем сообщения, отправляем стикер и удаляем) когда редактирование доходит то стикера то бот останавливается....
![Скриншот](http://dl4.joxi.net/drive/2019/11/01/0039/1078/2569270/70/800701d116.png)

**Comment by fgff** [comment]
> /media/MiHDD/bots/ivan # ./start.sh
> Traceback (most recent call last):
>   File "main.py", line 159, in <module>
>     asyncio.run(msgReplaceDelete())
>   File "/runners.py", line 43, in run
>   File "/base_events.py", line 579, in run_until_complete
>   File "main.py", line 62, in msgReplaceDelete
>     vk.messages.edit(peer_id=event.peer_id, message_id=h, message='ᅠ')
>   File "/opt/lib/python3.7/site-packages/vk_api/vk_api.py", line 681, in __call__
>     return self._vk.method(self._method, kwargs)
>   File "/opt/lib/python3.7/site-packages/vk_api/vk_api.py", line 646, in method
>     raise error
> vk_api.exceptions.ApiError: [920] Can't edit this kind of message

LOGS)))

**Comment by P2LOVE** [comment]
#9b7eb19

**Comment by P2LOVE** [comment]
9b7eb19c761713e10f908cbe3dbd93605579ec4c fix
