### ISSUE TITLE
Использование самописной библиотеки вместо vk_api

### ISSUE THREAD

**Issue by triedgriefdev** [P2LOVE/VK-UserSide-Bot#5]
Ты пытаешься сделать что-то асинхронное, при это используешь синхронную vk_api.
Можно использовать [vk.py](https://github.com/kesha1225/vk.py) но он не работает с User Long Poll`ом, так что правильным вариантом будет написание своей библиотеки.

**Comment by triedgriefdev** [comment]
+ желательно сделать полный rewrite.

**Comment by crinny** [comment]
- зачем

**Comment by P2LOVE** [comment]
Рефакторинг на vk.py уже давно был задуман и задумывался в ветке
https://github.com/P2LOVE/VK-UserSide-Bot/tree/vk.py-code-refactoring

Пока что мне лень его делать, но сам факт

**Comment by triedgriefdev** [comment]
Но vk.py не поддержует User Long Poll, прийдеться либо ждать либо сделать свою либу.

**Comment by P2LOVE** [comment]
Убрал попытки в асинхронность, про vk.py - ждем юзер лп
